preload = /home/matt/Pictures/wallpapers/nixos.png
preload = /home/matt/Pictures/wallpapers/nixos-dark.png

# The comma before the path tells hyprpaper to apply this to ALL monitors
wallpaper = ,/home/matt/Pictures/wallpapers/nixos-dark.png
