# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

$mainMod = SUPER
input {
    kb_options = caps:super
}


monitor = eDP-1, preferred, auto, 1
monitor = HDMI-A-2, preferred, auto-left, 1



$terminal = kitty
$fileManager = dolphin
# $menu = rofi


#KEYBINDINGS
bind = $mainMod, Return, exec, $terminal
bind = $mainMod SHIFT, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, D, exec, ~/.config/rofi/launchers/type-2/launcher.sh
bind = $mainMod, R, exec, pkill -9 waybar; waybar

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen, 0

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# --- Workspace Bindings ---
# Switch workspaces with mainMod + [1-5]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move active window to a workspace with mainMod + SHIFT + [1-5]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# --- Screenshot Keybindings (Save to folder AND copy to clipboard) ---

# Select an area: saves to ~/screenshots and copies to clipboard
bind = $mainMod SHIFT, S, exec, DEFAULT_TARGET_DIR=~/Pictures/Screenshots grimblast copysave area

# Full monitor capture: saves to ~/screenshots and copies to clipboard
bind = $mainMod, Print, exec, DEFAULT_TARGET_DIR=~/Pictures/Screenshots grimblast copysave output


exec-once = awww-daemon
exec-once = waybar
exec-once = swaync

general {
    # ... your other settings ...
    
    # A soft, elegant translucent gray-blue that blends beautifully with dark themes
    col.active_border = rgba(898989aa) 

    gaps_out = 12
}

decoration {
    # Controls how rounded your window corners are
    rounding = 10
    
    # Optional: Adds a subtle blur behind translucent windows
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}
