# font_family JetBrainsMono Nerd Font Mono
font_size 16

disable_ligatures no
enable_audio_bell no

shell zsh
shell_integration disabled

cursor_shape block
url_style curly

remember_window_size no
window_padding_width 20
cursor_blink_interval 0

background_opacity .75
background_blur 32

confirm_os_window_close 0
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0 
 
sync_to_monitor no

# BEGIN_KITTY_THEME
# Cherry Midnight
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
